// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono, Caveat } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import LocaleProvider from "@/components/LocaleProvider";
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const caveat = Caveat({
	subsets: ["latin", "cyrillic", "latin-ext"],
	variable: "--font-caveat",
	weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
	title: "LookFrame - Адаптивный просмотр сайтов на разных устройствах",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className="h-full" suppressHydrationWarning>
			<body className={`${geistSans.variable} ${geistMono.variable} ${caveat.variable} antialiased h-screen`}>
				<ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
					<LocaleProvider>
						{children}
					</LocaleProvider>
				</ThemeProvider>
				<Toaster />
			</body>
		</html>
	);
}
